name: Continous integration
on:
  push:
    branches:
      - main

jobs:
  On_workflow_call:
    uses: awsdevops-sbs/github-reusable-workflows/.github/workflows/ci.yml@main
    with:
      project_name: expense-frontend
      npm_install: false



